### ISSUE TITLE
Text editor - Copy / Paste problem

### ISSUE THREAD

**Issue by Relik77** [Relik77/factorio_computer_core#2]
>@wgorman says #1:
> One additional thought... I'm not very fond of the copy / paste functionality in the factorio text-box, as you probably already discovered factorio removes new lines. This makes it difficult to build more complex projects with the computer mod. One idea I had is allowing an external read only mount to the filesystem. I hacked in a single file into /external/test but I could imagine allowing other plugins to register new code snippets in that manner. Hacking around Lua I discovered the local text = [==[ ]==] functionality, that along with an import worked well for me!

This problem is directly related to factorio GUI, I opened a ticket on the official forum to have a return from them on the possible improvements with the new version of the Gui in the future version of factorio (0.17). And also have an opinion on what would be the most compatible as a workaround.
https://forums.factorio.com/viewtopic.php?f=25&t=54396

For my part, I continue to investigate to find a compatible multiplayer solution ;-)

**Comment by Relik77** [comment]
The latest factorio update seems to correct this GUI problem

**Comment by zachary-D** [comment]
On a related note, are the computer files available as raw text anywhere on the disk?  It'd be nice to be able to open them in a normal text editor.

**Comment by Relik77** [comment]
Factorio does not allow scripts to read files on your disk, it's only possible to write them.
As this did not allow me to develop a complete system I preferred to wait and see if an upcoming update of the game would allow me to develop something better.

If you want it I can look to enable a scripting feature to write your code on your disk, but you will still need to copy / paste your code from you disk into the console on Factorio for import it.

By the way, the copy / paste function works correctly now (Factorio corrected the problem of removing line breaks. Great !), which makes code editing in an external IDE and import code into the game more easy (and reciprocally).
