### ISSUE TITLE
Issue with os.wait()

### ISSUE THREAD

**Issue by wgorman** [Relik77/factorio_computer_core#3]
I've upgraded to your latest version, and I'm now experiencing an issue with os.wait().  With the latest update, I no longer can access local variables.  Here is a simple program example:

```
local i = 0

function callback() 
  term.write("i = " .. i)
end

os.wait(callback, 1)
```

This throws an error now, while in the previous version I could access i.  Is this expected behavior?

One other quick note... while you resolved the > 0 issue in one place, lan.lua line 26 has the same issue.  Thanks!

**Comment by Relik77** [comment]
Hi,

For the trouble with the local variable, it is related to the serialization / deserialization problem. The locally defined variable can not be correctly serialized :(
On the other hand, you have 3 ways to make your code work:
```lua
local i = 0

function callback(i) 
  term.write("i = " .. i)
end

-- Pass 'i' to os.wait, it will be returned during the callback call
os.wait(callback, 1, i)
```
```lua
local i = 0
-- Save i in an environment variable (here "myenv_1")
os.set("myenv_1", i)
function callback() 
-- Recover i from your environment variable
  local i = os.get("myenv_1")
  term.write("i = " .. i)
end

os.wait(callback, 1)
```
```lua
-- Set i in non-local variable
i = 0
function callback() 
  term.write("i = " .. i)
end

os.wait(callback, 1)
```

The 1st solution was the 1st implemented. The 2nd was to make the code more readable. 3rd is an appreciable accidental "edge effect" ^^

ok, I had not seen for the test of line 26. I made the change and it will be present in the next release

**Comment by Relik77** [comment]
Hi,

New version available, it corrects the point of "> 0" and add "os.require(filename)" function, for load code from another file.

If I later find another way to properly serialize local variables, I'll point it out. But currently I do not feel that it is possible to do otherwise :/
