### ISSUE TITLE
Please provide a Readme!

### ISSUE THREAD

**Issue by realvictorprm** [Relik77/factorio_computer_core#8]
I know this is _just_ a Factorio mod you might think.

I can tell you *no*! As soon as you put something on Github you decided it's worth to spread with other people so curious people like me start looking into it 😄 ! Your repository deserves a description, much appreciation comes with a ReadMe 👍 !

**Comment by Relik77** [comment]
Hi,

The Readme was present on the official website of Factorio. But no worries, I added it here too ;-)
